### ISSUE TITLE
Cybera Server setup

### ISSUE THREAD

**Issue by EJTang** [MEASHY/Mahjong-Solitaire#9]

**Comment by EJTang** [comment]
Cybera Edmonton did not have any more floating IPs for us to use. So I set one up in Calgary.

**Comment by Cirieneve** [comment]
Setup for Cybera still needs to be completed

**Comment by EJTang** [comment]
Cybera is set up and we have a simple version of the game deployed now.
The current deployment is through python's SimpleHTTPServer, and will be changed to flask once we finish adding the new Mahjong stuff to the flask routing

**Comment by EJTang** [comment]
Cybera is set up with flask now and is deployed on the server. Can be access by going to http://199.116.235.91:5000/mahjong_index as long as the server is up
